### ISSUE TITLE
Plotting circular plot output of Phase Set Enrichment Analysis

### ISSUE THREAD

**Issue by yimwy** [thomazbastiaanssen/kronos#2]
Hi, wonderful tool! 

I am looking for codes to plot circular plots similar to the outputs of Phase Set Enrichment Analysis (https://journals.sagepub.com/doi/10.1177/0748730416631895) and wondering if it can be produced using ggplot2 or kronos? 

Thanks!

**Comment by thomazbastiaanssen** [comment]
Many thanks for your interest. 
I hadn't seen PSEA before, thank you for sharing! It looks like a very reasonable method to me.

Kronos is not equipped to perform the PSEA procedure itself, as it does not perform any clustering or have a way to consider overarching pathways. 

However, if you already have the outcome of a PSEA in a table/data.frame and are looking for a way to plot it, ggplot2 can certainly do that. 
The source code of `gg_kronos_circle()` in kronos contains some ggplot2 code, that could be a good place to start in this case. 

Best wishes, 
Thomaz
