### ISSUE TITLE
is it possible to analyse omics data for a single group?

### ISSUE THREAD

**Issue by aromanowski** [thomazbastiaanssen/kronos#3]
Hi!
Thanks for coming up with this package. Did I understand correctly that this package can only be used to compare omics data between at least 2 groups (control and treated)? I am wondering if it is possible to do an omics analysis for a single group, where the only variable would be time of day.

Thanks!
Andres

**Comment by thomazbastiaanssen** [comment]
Hi, thanks for your interest! 
Kronos also supports rhythmic analysis without treatment groups. You can check out a demonstrative example in our readme, [here](https://github.com/thomazbastiaanssen/kronos?tab=readme-ov-file#1-analysing-rhythmicity-in-a-single-group). 

The only requirement is that you need at least four time points per day/cycle to be able to fit a cosinor model. 

Cheers, 
Thomaz

**Comment by aromanowski** [comment]
Thanks, I will give it a try and compare it to BioCycle 2.0 an Metacycle outputs!
